name: Atomic News
favicon: null
layout_spectrum: 0.5379911933559924
typography_spectrum: 0.010938413674011827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1310469948220998
  lightness: 0.6989419874735177
  saturation: 0.7229127723257989
  rhythmicContrast: 0.08633233257569373
purpose: []
