name: Atomic News
favicon: null
layout_spectrum: 0.5379911933559924
typography_spectrum: 0.010938413674011827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#007ee5'
    - '#0000ff'
    - '#0055ff'
    - '#000080'
    - '#008080'
  brandStrength: 0.25
  lightness: 0.6989419874735177
  saturation: 0.3125
  rhythmicContrast: 0.08633233257569373
purpose: []
